[package]
name = "wasm"
version = "0.1.0"
authors = ["prehonor <ryx666@sina.cn>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.18"
wasm-bindgen = "*"
clib = { path = "../baselib" }

